# Generated by Django 5.1.6 on 2025-10-27 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIA',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'CATEGORIA',
            },
        ),
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('web', 'Sitio Web'), ('crm', 'CRM interno')], default='web', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='PERSONAL',
            fields=[
                ('idPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='DIRECCION',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('dir_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='RegioCore.cliente')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'DIRECCION',
            },
        ),
        migrations.CreateModel(
            name='COTIZACION',
            fields=[
                ('idCotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('tipo_entrega', models.CharField(choices=[('domicilio', 'Envío a domicilio'), ('recogida', 'Recogida en tienda')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('total_estimado_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_estimado_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('web', 'Sitio Web'), ('crm', 'CRM interno')], default='web', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='RegioCore.cliente')),
                ('direccion_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegioCore.direccion')),
                ('personal_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegioCore.personal')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'COTIZACION',
            },
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='RegioCore.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='DETALLE_COTIZACION',
            fields=[
                ('idDetCotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_estimado_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_estimado_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='RegioCore.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegioCore.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotizacion',
                'verbose_name_plural': 'Detalles de Cotizaciones',
                'db_table': 'DETALLE_COTIZACION',
            },
        ),
    ]
