# Generated by Django 5.1.6 on 2025-10-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegioCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccion_envio',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='personal_responsable',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='activo',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
