# Generated by Django 5.1.6 on 2025-11-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegioCore', '0003_alter_categoria_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PERSONAL',
        ),
    ]
