# Generated by Django 5.1.6 on 2025-11-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegioCore', '0004_delete_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_cotizacion',
            name='activo',
        ),
    ]
