# Generated by Django 5.1.6 on 2025-11-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegioCore', '0005_remove_detalle_cotizacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado_domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
