# Generated by Django 5.1.6 on 2025-11-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegioCore', '0006_cotizacion_estado_domicilio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='total_estimado_max',
            new_name='total_estimado',
        ),
        migrations.RenameField(
            model_name='detalle_cotizacion',
            old_name='precio_estimado_max',
            new_name='precio_estimado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_max',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='total_estimado_min',
        ),
        migrations.RemoveField(
            model_name='detalle_cotizacion',
            name='precio_estimado_min',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_min',
        ),
    ]
