# Generated by Django 5.2.5 on 2025-11-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegioCore', '0007_rename_total_estimado_max_cotizacion_total_estimado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
